# HF Downloader Configuration

# Application settings
download_directory: ""
max_retries: 5
timeout_seconds: 3600
concurrent_downloads: 1
foreground: false

# File paths
database_path: ./hf_downloader.db
pid_file: ./hf_downloader.pid
models_file: ./config/models.json

# Hugging Face settings
# hf_token:  # Set via environment variable HF_TOKEN

# Network settings
chunk_size: 1048576  # 1MB
user_agent: hf-downloader/1.0.0

# Logging settings
log:
  level: 'DEBUG'
  file: './logs/hf_downloader.log'
  max_size: 10485760  # 10MB
  backup_count: 5
  rotation: '1 days'
  retention: '5 days'
  format: '<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> - <blue>[{process.id}]</blue> - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>'

# Monitoring settings
monitoring:
  health_check_interval: 60  # Health check interval in seconds (default: 60 = 1 minute)
  models_check_interval: 10  # Models file check interval in seconds (default: 60 = 1 minute)

# Schedule settings (will be created if none exists)
default_schedule:
  enabled: true
  type: daily
  time: "16:30"
  max_concurrent_downloads: 1
